apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: tanveerdace/tanveerimages:kuber1
      ports:
        - containerPort: 8081